#!bin/bash
#Creditos
echo -e "\e[1;32mCREDITOS AL CREADOR...!"
echo "Created by: JORY "
echo "Date: 09/08/2018"
echo "MAS NFORMACION:JORY.JY"
echo "Youtube: https://www.youtube.com/channel/UCBWt19pL7PfmfyT2i-ymQDA/featured?view_as=subscriber "
echo -e "\e[1;33mMensaje: \e[1;36mNUNCA DEJES DE APRENDER SOLO VAYA HACIA ADELANTE\e[0m"
